name: first ci
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup app
        run: make setup
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test


